- name: remove "splash"
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\""
#    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet autoinstall ds=nocloud\""
    state: present
  register: change_grub

- name:  update grub2
  shell: update-grub2
  when:  change_grub.changed
